# Generated by Django 3.1.6 on 2021-02-18 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('published_at', models.DateTimeField(default=datetime.datetime(2021, 2, 18, 21, 44, 21, 527294))),
            ],
        ),
    ]
